# Generated by Django 4.2.7 on 2023-11-04 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only 9 digits are allowed.", regex="^\\d{9}$"
                            )
                        ],
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("Sole proprietor", "Sole proprietor"),
                            ("Legal entity", "Legal entity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Animals", "Animals"),
                            ("Appliances", "Appliances"),
                            ("Children", "Children"),
                            ("Cleaning", "Cleaning"),
                            ("Computers", "Computers"),
                            ("Construction", "Construction"),
                            ("Education", "Education"),
                            ("Home repair", "Home repair"),
                            ("Other", "Other"),
                            ("Sports", "Sports"),
                            ("Transportation", "Transportation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("description", models.TextField(default=None, max_length=350)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
