# Generated by Django 4.2.7 on 2023-11-08 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_remove_client_name_client_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
    ]
