# Generated by Django 4.2.7 on 2023-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="comment",
            field=models.TextField(max_length=150, null=True),
        ),
    ]
