# Generated by Django 4.2.7 on 2023-11-13 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(default=None, max_length=350)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Animals", "Animals"),
                            ("Appliances", "Appliances"),
                            ("Children", "Children"),
                            ("Cleaning", "Cleaning"),
                            ("Computers", "Computers"),
                            ("Construction", "Construction"),
                            ("Education", "Education"),
                            ("Home repair", "Home repair"),
                            ("Other", "Other"),
                            ("Sports", "Sports"),
                            ("Transportation", "Transportation"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("offer", models.IntegerField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="client.client",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executor",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
